# Generated by Django 4.2.1 on 2023-07-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_academicmaster_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OptionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=50)),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.selectmaster')),
            ],
        ),
    ]
