# Generated by Django 4.2.1 on 2023-07-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_selectmaster_optionmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionmaster',
            name='select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='job.selectmaster'),
        ),
    ]
