# Generated by Django 4.2.1 on 2023-07-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_statemaster_citymaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyknownmaster',
            name='technology',
            field=models.CharField(blank=True, choices=[('PHP', 'PHP'), ('Laravel', 'Laravel'), ('Mysql', 'Mysql'), ('Oracle', 'Oracle'), ('Python', 'Python'), ('React', 'React')], max_length=30, null=True),
        ),
    ]
