# Generated by Django 4.2.1 on 2023-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_technologyknownmaster_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemaster',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='candidatemaster',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
