# Generated by Django 4.2.1 on 2023-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_candidatemaster_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemaster',
            name='prefer_location',
            field=models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Rajkot', 'Rajkot'), ('Bhavnagar', 'Bhavnagar')], max_length=30),
        ),
    ]
